name: Publish package to GitHub Packages
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout from GitHub
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install wasm dependencies
        run: cargo install wasm-pack

      - name: Test
        run: wasm-pack test --node

      - name: Compile Wasm
        run: wasm-pack build --target bundler

      - name: Modify package name
        run: |
         sed -i -e 's|"name": "stark-crypto-wrapper-wasm"|"name": "@x10xchange/stark-crypto-wrapper-wasm"|g' pkg/package.json

      - name: Packaged wasm
        run: wasm-pack pack

      - name: Publish wasm
        run: wasm-pack publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}